-- 코드를 입력하세요
SELECT YEAR(OS.sales_date) YEAR, MONTH(OS.sales_date) MONTH, UI.gender GENDER, COUNT(DISTINCT UI.user_id)
FROM USER_INFO UI, ONLINE_SALE OS
WHERE UI.user_id = OS.user_id AND GENDER is not null
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER