-- 코드를 입력하세요
WITH TMP AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(SALES_DATE) YEAR, 
       MONTH(SALES_DATE) MONTH,
       COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM TMP), 1) AS RATIO
FROM ONLINE_SALE
    JOIN TMP USING(USER_ID)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2