SELECT *
FROM
(SELECT J.FLAVOR
FROM JULY J LEFT JOIN FIRST_HALF H 
 ON J.SHIPMENT_ID = H.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY SUM(NVL(J.TOTAL_ORDER, 0) + NVL(H.TOTAL_ORDER, 0)) DESC
)
WHERE ROWNUM <=3