-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER A, USED_GOODS_BOARD B
WHERE A.USER_ID = B.WRITER_ID AND B.STATUS LIKE 'DONE'
GROUP BY A.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY 3 ASC