-- 코드를 입력하세요

SELECT HISTORY_ID, 
       ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)
       *(100-IF(DISCOUNT_RATE IS NULL, 0, DISCOUNT_RATE))/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B 
ON A.CAR_ID = B.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON A.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE = (CASE WHEN DATEDIFF(END_DATE,START_DATE)+1>='90' THEN '90일 이상'
                            WHEN DATEDIFF(END_DATE,START_DATE)+1>='30' THEN '30일 이상'
                            WHEN DATEDIFF(END_DATE,START_DATE)+1>='7' THEN '7일 이상'
                          ELSE NULL END)
WHERE 1=1                          
AND A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, B.HISTORY_ID DESC;