-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME,date_format(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR A, BOOK B 
WHERE B.CATEGORY LIKE "경제" AND A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY B.PUBLISHED_DATE