-- 코드를 입력하세요
SELECT DISTINCT B.CAR_ID
FROM  CAR_RENTAL_COMPANY_CAR A,CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_TYPE = '세단' AND A.CAR_ID = B.CAR_ID
AND DATE_FORMAT(B.START_DATE, '%m') = 10
ORDER BY A.CAR_ID DESC